spring.application.name=carpooling

# ========== PROFIL ACTIF ==========
spring.profiles.active=dev

# ========== CORS ==========
cors.allowed-origins=http://localhost:5173,http://localhost:3000,http://localhost:8080

# ========== DATABASE ==========
spring.datasource.url=jdbc:postgresql://postgres:5432/carpooling
spring.datasource.username=myuser
spring.datasource.password=mypassword
spring.datasource.driver-class-name=org.postgresql.Driver

# ========== JPA/HIBERNATE ==========
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

# ========== SERVER ==========
server.port=8080

# ========== JWT CONFIGURATION ==========
jwt.secret-key=${JWT_SECRET_KEY:SCloWsuh194DKKYEUbd8eLLU7thqzyHAqFaMw0u5YS/z2rX7gLBbX9+tKMgPuvCz}
jwt.issuer=carpooling-api
jwt.expiration-ms=900000

ors.api-key=eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6ImVjMGU5YWFlNTZhNjQzMzc4ZmJhYWMyZDJmMmM5MjE1IiwiaCI6Im11cm11cjY0In0=

# ========== Swagger UI ==========
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operations-sorter=method

# ========== LOGGING ==========
logging.level.root=INFO
logging.level.com.cda.carpooling=DEBUG

logging.level.org.hibernate=WARN
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=WARN
logging.level.org.hibernate.orm=WARN

logging.level.org.springframework=WARN
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.boot=INFO

logging.level.com.zaxxer.hikari=WARN

logging.pattern.console=%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n